# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Move pull request to proper column

on:
  pull_request:
    types: [review_requested, opened, edited]

env:
  in_review: 'In Review'
  in_progress: 'In Progress'
  user: 'mohamedSabry0'
  project_id: 13
  token: ${{ secrets.GHPROJECT }}

jobs:
  pr_reviewrequested:
    name: pr_reviewrequested
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'review_requested'
    steps:
      - name: Move PR to ${{ env.in_review }}
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        with:
          gh_token: ${{ env.token }}
          user: ${{ env.user }}
          # organization: sample-org
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.in_review }} # Target status
          move_related_issues: true

  pr_opened_edited:
    name: pr_opened_edited
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'edited')
    steps:
      - name: Move PR to ${{env.in_progress}}
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        with:
          gh_token: ${{ env.token }}
          user: ${{ env.user }}
          # organization: sample-org
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.in_progress }} # Target status
          move_related_issues: true
