name: Get linked issues
on:
  pull_request:
    types: [opened, edited]
  push:

env:
  in_review: 'In Review'
  user: 'mohamedSabry0'
  project_id: 13
  token: ${{ secrets.GHPROJECT }}

jobs:
  print_linked_issues:
    name: Print linked issues
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to ${{ env.in_review }}
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        with:
          gh_token: ${{ env.token }}
          user: ${{ env.user }}
          # organization: sample-org
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.pull_request.closingIssuesReferences.first.node_id }}
          status_value: ${{ env.in_review }}
      - name: Print linked issues
        run: |
          echo "PR linked issues: ${{ github.event.pull_request.closingIssuesReferences }}"
          echo "PR ${{ github.event.pull_request.number }}"
          echo "PR ${{ github.event.pull_request.closingIssuesReferences.nodes }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GHPROJECT }}

  # get-linked-issues:
  #   name: Get linked issues
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get issues
  #       id: get-issues
  #       uses: mondeja/pr-linked-issues-action@v2
  #       with:
  #         add_links_by_content: |
  #           **Closes**: #{issue_number}
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Print linked issue numbers
  #       run: echo ${{ steps.get-issues.outputs.issues }}
  #     - name: Get issues
  #       id: get-issues
  #       uses: mondeja/pr-linked-issues-action@v2
  #       # with:
  #       #   repository_owner: 'mohamedSabry0'
  #       #   repository_name: 'appointments_app'
  #       #   pull_request: ${{ github.event.pull_request.number }}
  #       # env:
  #       #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     - name: move issues to ${{ env.in_progress }}
  #       uses: leonsteinhaeuser/project-beta-automations@v2.2.1
  #       with:
  #         gh_token: ${{ env.token }}
  #         user: ${{ env.user }}
  #         # organization: sample-org
  #         project_id: ${{ env.project_id }}
  #         resource_node_id: ${{ steps.get-issues.outputs.issues }}
  #         status_value: ${{ env.in_progress }} # Target status
